### ISSUE TITLE
64 bit OS releases

### ISSUE THREAD

**Issue by rosterloh** [prepkg/opencv-raspberrypi#1]
Is there any chance you will build for 64 bit OSs in the future?

**Comment by prepkg** [comment]
Raspberry Pi OS 64-bit builds are still only in a beta stage. Right now I don't have any plans to build for 64-bit OS. When 64-bit OS will be released, I will build OpenCV binaries for 64-bit OS as well.

**Comment by rosterloh** [comment]
Thanks. I'll keep an eye out

**Comment by prepkg** [comment]
@rosterloh binaries are ready for Raspberry Pi OS 64-bit. You can download the opencv_64.deb from releases page.
