### ISSUE TITLE
It doesn't work on latest bullseye raspberry os lite

### ISSUE THREAD

**Issue by highfreq** [prepkg/opencv-raspberrypi#2]
Tried to install it this morning on the latest lite 32 bit burned with raspberry imager, i get a numpy error, i think it is due to bulleye (latest raspian) not compatible.

**Comment by prepkg** [comment]
Right now OpenCV binaries provided in this repository are compatible with Raspberry Pi OS Buster (32-bit).

**Comment by highfreq** [comment]
Ok, thank you.

**Comment by prepkg** [comment]
@highfreq binaries updated from Buster to Bullseye. You can download `opencv.deb` from releases page.

**Comment by highfreq** [comment]
Great!! Thank you.
