### ISSUE TITLE
Problem with cv.imshow function 

### ISSUE THREAD

**Issue by santana-atma** [prepkg/opencv-raspberrypi#3]
I am trying to test some example from official example [here](https://docs.opencv.org/4.x/db/deb/tutorial_display_image.html), but i got unexpected result like this :

> ❯ python3 display_image.py
> Traceback (most recent call last):
>   File "/home/pi/Desktop/display_image.py", line 6, in <module>
>     cv.imshow("Display window", img)
> cv2.error: OpenCV(4.5.5) /home/pi/opencv-src/modules/highgui/src/window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

I checked if my installation is succesfull using **opencv_version** before, which is succesfully returned version value **"4.5.5".**
I also tried some otherbasic  opencv function like **cv2.imread()** to convert image into grayscale and write it using **cv2.imwrite()** , and it was resulted grayscale image as intended.
Tested this using Raspberry Pi 3B+ with OS Raspbian 11 Bullseye 32 bit, installed on 16 GB microSD.

**Comment by prepkg** [comment]
Right now OpenCV binaries provided in this repository are built without GUI support. You can check build information: 
https://github.com/prepkg/opencv-raspberrypi/blob/master/build_information.txt#L43

**Comment by santana-atma** [comment]
@prepkg ah, so it was not implemented yet. my mistake for not fully understanding that build_information file. thank you for clarifying this issue.

**Comment by InfiniteCoder01** [comment]
I can't seem to get GUI support on 4.10+, but with 4.9 it worked fine before (for some reason now I'm getting TBB task linking errors)
