### ISSUE TITLE
Failed to allocate required memory

### ISSUE THREAD

**Issue by EntnyJill** [prepkg/opencv-raspberrypi#4]
Hello.

Prerequisites: Raspberry Pi 3b, Raspbian Bullseye 64bit, latest prepkg/opencv-raspberrypi installed.

I'm trying to create VideoCapture from OpenCV for python:
```
import cv2
cap = cv2.VideoCapture(0)
```
But get error:
```
[ WARN:0@3.949] global cap_gstreamer.cpp:2784 handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Failed to allocate required memory.
[ WARN:0@3.952] global cap_gstreamer.cpp:1679 open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@3.952] global cap_gstreamer.cpp:1164 isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```

The reason of the issue is incompatibility with libcamera in Raspbian Bullseye as stated here:
https://github.com/raspberrypi/libcamera-apps/issues/487

Can you modify your build to overcome this problem? Or it's necessary to rebuild libcamera or use legacy camera stack?

**Comment by prepkg** [comment]
Hi,
Currently, I am unable to test your scenario. Can you try to use:
`cap = cv2.VideoCapture(cv2.CAP_V4L2)` or `cap = cv2.VideoCapture(cv2.CAP_FFMPEG)`

**Comment by EntnyJill** [comment]
> Hi, Currently, I am unable to test your scenario. Can you try to use: `cap = cv2.VideoCapture(cv2.CAP_V4L2)` or `cap = cv2.VideoCapture(cv2.CAP_FFMPEG)`

I tried these commands but after it I receive empty capture without any image. I found solution to overcome this issue: I switched to legacy camera stack in raspi-config, and VideoCapture works as it should be. It may be useful for someone to modify your repository README and state that for VideoCapture legacy stack should be used.

**Comment by prepkg** [comment]
Thank you for letting me know!

**Comment by surak** [comment]
I have found that if you have it, the `libcamerify` utility works. I think I got it with Arducam.
