### ISSUE TITLE
Missing aruco.hpp

### ISSUE THREAD

**Issue by BreizhHardware** [prepkg/opencv-raspberrypi#6]
Hi,
I was trying to compile my opencv project on my raspberry pi 3 using your precompile cpp opencv and It apear that the aruco module wasn't install
![image](https://github.com/prepkg/opencv-raspberrypi/assets/72651575/2326c53b-329d-407f-bf3f-0bc7251f92fa)
So I was asking if it was possible to add it in a future release.

**Comment by prepkg** [comment]
Hi,
The aruco module is exclusively found in the [opencv_contrib](https://github.com/opencv/opencv_contrib/tree/4.x/modules/aruco) repository. I am providing precompiled OpenCV binaries sourced from the primary [OpenCV](https://github.com/opencv/opencv) repository. I will consider creating a precompiled opencv_contrib package tailored for Raspberry Pi.
