### ISSUE TITLE
Broken Python bindings - can't import cv2

### ISSUE THREAD

**Issue by mechanburg** [prepkg/opencv-raspberrypi#7]
Fresh install of Bookworm, followed the guide here: https://lindevs.com/install-precompiled-opencv-on-raspberry-pi. Seems like install went well except for a warning: 

>`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'opencv' instead of './opencv_64.deb'
The following NEW packages will be installed:
  opencv
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/11.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/pi/opencv_64.deb opencv arm64 4.9.0-1 [11.2 MB]
Selecting previously unselected package opencv.
(Reading database ... 150364 files and directories currently installed.)
Preparing to unpack /home/pi/opencv_64.deb ...
Unpacking opencv (4.9.0-1) ...
Setting up opencv (4.9.0-1) ...
N: Download is performed unsandboxed as root as file '/home/pi/opencv_64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`

Still, I get proper build information when I create the main.cpp file on the blog article. However, main.py does not work due to a failed "import cv2": 

>`Traceback (most recent call last):
  File "/home/pi/main.py", line 1, in <module>
    import cv2
  File "/usr/local/lib/python3.11/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.11/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /usr/local/lib/libopencv_core.so.409: undefined symbol: _ZTIN3tbb4taskE`

Thanks for any help you can provide.

**Comment by prepkg** [comment]
Hi. Can you provide details using the following commands:
* cat /etc/rpi-issue
* cat /sys/firmware/devicetree/base/model
* python -V
* ls /usr/local/lib | grep opencv

**Comment by mechanburg** [comment]
Thanks for getting back. I've experimented a lot and found issues with the latest RPI OS Bookworm installed as of today, I am not able to install any Python packages using pip due to it being an "externally managed environment". After removing that setting (sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED) prior to installing the .deb file, seems like it's functioning with Python now.

**Comment by mechanburg** [comment]
Raspberry Pi Compute Module 4 Rev 1.1
Python 3.11.2
libopencv_calib3d.so
libopencv_calib3d.so.409
libopencv_calib3d.so.4.9.0
libopencv_core.so
libopencv_core.so.409
libopencv_core.so.4.9.0
libopencv_dnn.so
libopencv_dnn.so.409
libopencv_dnn.so.4.9.0
libopencv_features2d.so
libopencv_features2d.so.409
libopencv_features2d.so.4.9.0
libopencv_flann.so
libopencv_flann.so.409
libopencv_flann.so.4.9.0
libopencv_gapi.so
libopencv_gapi.so.409
libopencv_gapi.so.4.9.0
libopencv_highgui.so
libopencv_highgui.so.409
libopencv_highgui.so.4.9.0
libopencv_imgcodecs.so
libopencv_imgcodecs.so.409
libopencv_imgcodecs.so.4.9.0
libopencv_imgproc.so
libopencv_imgproc.so.409
libopencv_imgproc.so.4.9.0
libopencv_ml.so
libopencv_ml.so.409
libopencv_ml.so.4.9.0
libopencv_objdetect.so
libopencv_objdetect.so.409
libopencv_objdetect.so.4.9.0
libopencv_photo.so
libopencv_photo.so.409
libopencv_photo.so.4.9.0
libopencv_stitching.so
libopencv_stitching.so.409
libopencv_stitching.so.4.9.0
libopencv_videoio.so
libopencv_videoio.so.409
libopencv_videoio.so.4.9.0
libopencv_video.so
libopencv_video.so.409
libopencv_video.so.4.9.0
